openapi: "3.0.0"
info:
  title: "Habit Tracker API"
  description: "API for managing habits and habit logs"
  version: "1.0.0"
servers:
  - url: "http://localhost:9002"
    description: "Local development server"

paths:
  /habits/create:
    post:
      summary: "Create a new habit"
      description: "Creates a new habit with the provided details."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                habit:
                  type: string
                  example: "Exercise"
                description:
                  type: string
                  example: "Daily workout for health"
                interval:
                  type: string
                  example: "daily"
                goal:
                  type: integer
                  example: 30
      responses:
        "201":
          description: "Habit created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  habit:
                    type: object
                    description: "Created habit details"
                  message:
                    type: string
                    example: "Data added successfully"

  /habits/list:
    get:
      summary: "Retrieve list of habits"
      description: "Retrieves a list of all existing habits."
      responses:
        "200":
          description: "List of habits"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    habit:
                      type: string
                      example: "Exercise"
                    description:
                      type: string
                      example: "Daily workout for health"
                    interval:
                      type: string
                      example: "daily"
                    goal:
                      type: integer
                      example: 30

  /habits/delete/{habit_id}:
    delete:
      summary: "Delete a habit"
      description: "Deletes a habit with the specified ID."
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: string
          description: "ID of the habit to delete"
      responses:
        "200":
          description: "Habit deleted successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: "habit deleted successfully"
        "404":
          description: "Habit not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Habit not found"


  /habits/get/{habit_id}:
    get:
      summary: "Get a habit"
      description: "Retrieve a habit with the specified ID."
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: integer
          description: "ID of the habit to retrieve"
      responses:
        "200":
          description: "Habit retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  habit:
                    type: string
                    example: "Exercise"
                  description:
                    type: string
                    example: "Daily workout for health"
                  interval:
                    type: string
                    example: "daily"
                  goal:
                    type: integer
                    example: 30

        "404":
          description: "Habit not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Habit not found"


  /habits/update/{habit_id}:
    put:
      summary: "update a new habit"
      description: "Update a habit with the specified ID"
      parameters:
        - in: path
          name: habit_id
          required: true
          schema:
            type: string
          description: "ID of the habit to update"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                habit:
                  type: string
                  example: "Exercise"
                description:
                  type: string
                  example: "Daily workout for health"
                interval:
                  type: string
                  example: "daily"
                goal:
                  type: integer
                  example: 30
      responses:
        "201":
          description: "Habit updated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  habit:
                    type: object
                    description: "Updated habit details"
                  message:
                    type: string
                    example: "Data added successfully"